= We are hiring
Peter Lawrey

== Low latency Java Developers

We are looking for Contract or Permenant employees to develop solutions for clients, development of products, and support for those products.

It’s essential that you are :

 - extremely strong in core java ( at-least 5 years experience ), and willing to read the existing code to understand the problem domain.
 - able to work with minimal assistance.
 - customer focused, good communicator and have a passion for working with clients.
 - able to work on client site ( on average likely to be less than 50% of the time )
 - be able to work from home, with a good internet connection.
 - based in London
 - knowledge/experience of investment banking 
 - good English
 - Linux

An advantage ( but not essential )

 - C++
 - eFX
 - good at documentation 
 - methodical
 - personable
 - previous experience of :
    * chronicle 
    * teamCity
    * intellij idea

== About us

Most people know of Chronicle by our first open source project called Chronicle Queue,  We have since developed a number of other open-source projects such as Chronicle-Map, Chronicle-Engine and our latest commercial offering Chronicle-Fix. All these projects have a few things in common, they all focus on getting C like performance from java, they all use off-heap storage to provide very fast interprocess communication between processes on the same computer.  

Most of our clients are investment banks in London and New York.

=== If you are interested

Send me your CV, salary expectations and availability to peter.lawrey@chronicle.software
